spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: pinsily96
    driver-class-name: com.mysql.cj.jdbc.Driver
#  resources:
#    static-locations: classpath:/templates

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml

server:
  servlet:
    session:
      timeout: 6000s
      cookie:
        name: mysession
        max-age: 6000s