package com.pinsily.car_rental.dao.mappers;

import com.pinsily.car_rental.dao.domain.Car;
import com.pinsily.car_rental.dao.domain.CarExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    int countByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    int deleteByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    int deleteByPrimaryKey(Integer index);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    int insert(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    int insertSelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    List<Car> selectByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    Car selectByPrimaryKey(Integer index);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    int updateByExampleSelective(@Param("record") Car record, @Param("example") CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    int updateByExample(@Param("record") Car record, @Param("example") CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    int updateByPrimaryKeySelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    int updateByPrimaryKey(Car record);
}