package com.pinsily.car_rental.dao.domain;

public class Car {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.index
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    private Integer index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.model
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.stock
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.index
     *
     * @return the value of t_car.index
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.index
     *
     * @param index the value for t_car.index
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.model
     *
     * @return the value of t_car.model
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.model
     *
     * @param model the value for t_car.model
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.stock
     *
     * @return the value of t_car.stock
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.stock
     *
     * @param stock the value for t_car.stock
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}