package com.pinsily.car_rental.dao.domain;

import java.util.Date;

public class Car {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.findex
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    private Integer index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.model
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.stock
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.version
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.create_time
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.modify_time
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.findex
     *
     * @return the value of t_car.findex
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public Integer getIndex() {
        return index;
    }

    public Integer getFindex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.findex
     *
     * @param findex the value for t_car.findex
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public void setIndex(Integer findex) {
        this.index = findex;
    }

    public void setFindex(Integer findex) {
        this.index = findex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.model
     *
     * @return the value of t_car.model
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.model
     *
     * @param model the value for t_car.model
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.stock
     *
     * @return the value of t_car.stock
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.stock
     *
     * @param stock the value for t_car.stock
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.version
     *
     * @return the value of t_car.version
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.version
     *
     * @param version the value for t_car.version
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.create_time
     *
     * @return the value of t_car.create_time
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.create_time
     *
     * @param createTime the value for t_car.create_time
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.modify_time
     *
     * @return the value of t_car.modify_time
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.modify_time
     *
     * @param modifyTime the value for t_car.modify_time
     *
     * @mbggenerated Sat Jul 02 21:38:47 CST 2022
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}