package com.pinsily.car_rental.dao.domain;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.index
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    private Integer index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.uid
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.car_id
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.start_time
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.end_time
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.index
     *
     * @return the value of t_order.index
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.index
     *
     * @param index the value for t_order.index
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.uid
     *
     * @return the value of t_order.uid
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.uid
     *
     * @param uid the value for t_order.uid
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.car_id
     *
     * @return the value of t_order.car_id
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.car_id
     *
     * @param carId the value for t_order.car_id
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.start_time
     *
     * @return the value of t_order.start_time
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.start_time
     *
     * @param startTime the value for t_order.start_time
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.end_time
     *
     * @return the value of t_order.end_time
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.end_time
     *
     * @param endTime the value for t_order.end_time
     *
     * @mbggenerated Fri Jul 01 20:46:07 CST 2022
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}