package com.pinsily.car_rental.dao.domain;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.findex
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    private Integer index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.uid
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.car_id
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.car_model
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    private String carModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.start_time
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.end_time
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.findex
     *
     * @return the value of t_order.findex
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.findex
     *
     * @param findex the value for t_order.findex
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public void setIndex(Integer findex) {
        this.index = findex;
    }

    public Integer getFindex() {
        return index;
    }

    public void setFindex(Integer findex) {
        this.index = findex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.uid
     *
     * @return the value of t_order.uid
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.uid
     *
     * @param uid the value for t_order.uid
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.car_id
     *
     * @return the value of t_order.car_id
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.car_id
     *
     * @param carId the value for t_order.car_id
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.car_model
     *
     * @return the value of t_order.car_model
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public String getCarModel() {
        return carModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.car_model
     *
     * @param carModel the value for t_order.car_model
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public void setCarModel(String carModel) {
        this.carModel = carModel == null ? null : carModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.start_time
     *
     * @return the value of t_order.start_time
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.start_time
     *
     * @param startTime the value for t_order.start_time
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.end_time
     *
     * @return the value of t_order.end_time
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.end_time
     *
     * @param endTime the value for t_order.end_time
     *
     * @mbggenerated Sat Jul 02 21:38:48 CST 2022
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}